FEEDS = [
    {
        "id": "dbt_core",
        "name": "dbt-core Releases",
        "url": "https://github.com/dbt-labs/dbt-core/releases.atom",
        "category": "Data Tools",
        "platform": "dbt",
        "type": "releases",
    },
    {
        "id": "dbt_blog",
        "name": "dbt blog releases",
        "url": "https://www.getdbt.com/blog",
        "category": "Data Tools",
        "platform": "dbt",
        "type": "blog",
    },
    {
        "id": "dbt_fusion",
        "name": "dbt fusion releases",
        "url": "https://github.com/dbt-labs/dbt-fusion/releases.atom",
        "category": "Data Tools",
        "platform": "dbt",
        "type": "blog",
    },
    {
        "id": "snowflake_blog",
        "name": "Snowflake Blog",
        "url": "https://publish-p57963-e462109.adobeaemcloud.com/feed/?lang=en",
        "category": "Data Tools",
        "platform": "Snowflake",
        "type": "blog",
    },
    {
        "id": "snowflake_connector",
        "name": "Snowflake Connector Python",
        "url": "https://github.com/snowflakedb/snowflake-connector-python/releases.atom",
        "category": "Data Tools",
        "platform": "Snowflake",
        "type": "releases",
    },
    {
        "id": "anthropic_sdk",
        "name": "Anthropic SDK Python",
        "url": "https://github.com/anthropics/anthropic-sdk-python/releases.atom",
        "category": "AI",
        "platform": "Anthropic",
        "type": "releases",
    },
    {
        "id": "claude_code",
        "name": "Claude Code Releases",
        "url": "https://github.com/anthropics/claude-code/releases.atom",
        "category": "AI",
        "platform": "Anthropic",
        "type": "releases",
    },
    {
        "id": "openai_news",
        "name": "OpenAI News",
        "url": "https://openai.com/news/rss.xml",
        "category": "AI",
        "platform": "OpenAI",
        "type": "blog",
    },
    {
        "id": "openai_sdk",
        "name": "OpenAI Python SDK",
        "url": "https://github.com/openai/openai-python/releases.atom",
        "category": "AI",
        "platform": "OpenAI",
        "type": "releases",
    },
    {
        "id": "google_ai_blog",
        "name": "Google AI Blog",
        "url": "https://blog.google/technology/ai/rss/",
        "category": "AI",
        "platform": "Google",
        "type": "blog",
    },
    {
        "id": "google_dev_blog",
        "name": "Google Developers Blog",
        "url": "https://developers.googleblog.com/feeds/posts/default?alt=rss",
        "category": "AI",
        "platform": "Google",
        "type": "blog",
    },
    {
        "id": "gemini_releases",
        "name": "Gemini Release Notes",
        "url": "https://docs.cloud.google.com/feeds/gemini-release-notes.xml",
        "category": "AI",
        "platform": "Google",
        "type": "releases",
    },
    {
        "id": "vertex_releases",
        "name": "Vertex AI Release Notes",
        "url": "https://docs.cloud.google.com/feeds/vertex-ai-release-notes.xml",
        "category": "AI",
        "platform": "Google",
        "type": "releases",
    },
    {
        "id": "gcp_release_notes",
        "name": "Google Cloud Release Notes",
        "url": "https://cloud.google.com/feeds/gcp-release-notes.xml",
        "category": "Cloud",
        "platform": "Google Cloud",
        "type": "releases",
    },
    {
        "id": "gcp_blog",
        "name": "Google Cloud Blog",
        "url": "https://cloud.google.com/blog/rss",
        "category": "Cloud",
        "platform": "Google Cloud",
        "type": "blog",
    },
    {
        "id": "bigquery_releases",
        "name": "BigQuery Release Notes",
        "url": "https://cloud.google.com/feeds/bigquery-release-notes.xml",
        "category": "Cloud",
        "platform": "Google Cloud",
        "type": "releases",
    },
    {
        "id": "databricks_blog",
        "name": "Databricks Blog",
        "url": "https://www.databricks.com/feed",
        "category": "Data Tools",
        "platform": "Databricks",
        "type": "blog",
    },
    {
        "id": "databricks_sdk_python",
        "name": "Databricks SDK Python",
        "url": "https://github.com/databricks/databricks-sdk-py/releases.atom",
        "category": "Data Tools",
        "platform": "Databricks",
        "type": "releases",
    },
    {
        "id": "databricks_sdk_go",
        "name": "Databricks SDK Go",
        "url": "https://github.com/databricks/databricks-sdk-go/releases.atom",
        "category": "Data Tools",
        "platform": "Databricks",
        "type": "releases",
    },
    # AWS
    {
        "id": "aws_whats_new",
        "name": "AWS What's New",
        "url": "https://aws.amazon.com/about-aws/whats-new/recent/feed/",
        "category": "Cloud",
        "platform": "AWS",
        "type": "releases",
    },
    {
        "id": "aws_blog",
        "name": "AWS Blog",
        "url": "https://aws.amazon.com/blogs/aws/feed/",
        "category": "Cloud",
        "platform": "AWS",
        "type": "blog",
    },
    # Databases
    {
        "id": "duckdb",
        "name": "DuckDB Releases",
        "url": "https://github.com/duckdb/duckdb/releases.atom",
        "category": "Data Tools",
        "platform": "DuckDB",
        "type": "releases",
    },
    {
        "id": "mongodb_blog",
        "name": "MongoDB Blog",
        "url": "https://www.mongodb.com/blog/rss",
        "category": "Data Tools",
        "platform": "MongoDB",
        "type": "blog",
    },
    {
        "id": "redis_releases",
        "name": "Redis Releases",
        "url": "https://github.com/redis/redis/releases.atom",
        "category": "Data Tools",
        "platform": "Redis",
        "type": "releases",
    },
    {
        "id": "iceberg_releases",
        "name": "Apache Iceberg Releases",
        "url": "https://github.com/apache/iceberg/releases.atom",
        "category": "Data Tools",
        "platform": "Apache Iceberg",
        "type": "releases",
    },
    {
        "id": "delta_lake",
        "name": "Delta Lake Releases",
        "url": "https://github.com/delta-io/delta/releases.atom",
        "category": "Data Tools",
        "platform": "Delta Lake",
        "type": "releases",
    },
    {
        "id": "polars",
        "name": "Polars Releases",
        "url": "https://github.com/pola-rs/polars/releases.atom",
        "category": "Data Tools",
        "platform": "Polars",
        "type": "releases",
    },
    {
        "id": "airbyte",
        "name": "Airbyte Releases",
        "url": "https://github.com/airbytehq/airbyte/releases.atom",
        "category": "Data Tools",
        "platform": "Airbyte",
        "type": "releases",
    },
    # Orchestration
    {
        "id": "airflow",
        "name": "Apache Airflow Releases",
        "url": "https://github.com/apache/airflow/releases.atom",
        "category": "Orchestration",
        "platform": "Apache Airflow",
        "type": "releases",
    },
    {
        "id": "prefect",
        "name": "Prefect Releases",
        "url": "https://github.com/PrefectHQ/prefect/releases.atom",
        "category": "Orchestration",
        "platform": "Prefect",
        "type": "releases",
    },
    # AI Frameworks
    {
        "id": "huggingface_blog",
        "name": "Hugging Face Blog",
        "url": "https://huggingface.co/blog/feed.xml",
        "category": "AI",
        "platform": "Hugging Face",
        "type": "blog",
    },
    {
        "id": "ollama",
        "name": "Ollama Releases",
        "url": "https://github.com/ollama/ollama/releases.atom",
        "category": "AI",
        "platform": "Ollama",
        "type": "releases",
    },
    {
        "id": "langchain",
        "name": "LangChain Releases",
        "url": "https://github.com/langchain-ai/langchain/releases.atom",
        "category": "AI",
        "platform": "LangChain",
        "type": "releases",
    },
    {
        "id": "llamaindex",
        "name": "LlamaIndex Releases",
        "url": "https://github.com/run-llama/llama_index/releases.atom",
        "category": "AI",
        "platform": "LlamaIndex",
        "type": "releases",
    },
    # Streamlit
    {
        "id": "streamlit_releases",
        "name": "Streamlit Releases",
        "url": "https://github.com/streamlit/streamlit/releases.atom",
        "category": "Data Tools",
        "platform": "Streamlit",
        "type": "releases",
    },
    {
        "id": "streamlit_blog",
        "name": "Streamlit Blog",
        "url": "https://blog.streamlit.io/feed/",
        "category": "Data Tools",
        "platform": "Streamlit",
        "type": "blog",
    },
    # Python
    {
        "id": "python_releases",
        "name": "Python Releases",
        "url": "https://github.com/python/cpython/releases.atom",
        "category": "Data Tools",
        "platform": "Python",
        "type": "releases",
    },
    # Apache Spark
    {
        "id": "spark_releases",
        "name": "Apache Spark Releases",
        "url": "https://github.com/apache/spark/releases.atom",
        "category": "Data Tools",
        "platform": "Apache Spark",
        "type": "releases",
    },
    # Dagster
    {
        "id": "dagster_releases",
        "name": "Dagster Releases",
        "url": "https://github.com/dagster-io/dagster/releases.atom",
        "category": "Orchestration",
        "platform": "Dagster",
        "type": "releases",
    },
    # Azure
    {
        "id": "azure_updates",
        "name": "Azure Updates",
        "url": "https://azure.microsoft.com/en-us/updates/feed/",
        "category": "Cloud",
        "platform": "Azure",
        "type": "releases",
    },
    # GitHub
    {
        "id": "github_blog",
        "name": "GitHub Blog",
        "url": "https://github.blog/feed/",
        "category": "AI",
        "platform": "GitHub",
        "type": "blog",
    },
    {
        "id": "github_changelog",
        "name": "GitHub Changelog",
        "url": "https://github.blog/changelog/feed/",
        "category": "AI",
        "platform": "GitHub",
        "type": "releases",
    },
    # Mistral AI
    {
        "id": "mistral_releases",
        "name": "Mistral AI Releases",
        "url": "https://github.com/mistralai/mistral-inference/releases.atom",
        "category": "AI",
        "platform": "Mistral AI",
        "type": "releases",
    },
    # AWS ML
    {
        "id": "aws_ml_blog",
        "name": "AWS Machine Learning Blog",
        "url": "https://aws.amazon.com/blogs/machine-learning/feed/",
        "category": "AI",
        "platform": "AWS",
        "type": "blog",
    },
    # Marketing APIs
    {
        "id": "google_ads_blog",
        "name": "Google Ads Developer Blog",
        "url": "https://ads-developers.googleblog.com/feeds/posts/default",
        "category": "Marketing",
        "platform": "Google Ads",
        "type": "blog",
    },
    {
        "id": "google_search_blog",
        "name": "Google Search Blog",
        "url": "https://blog.google/products/search/rss/",
        "category": "Marketing",
        "platform": "Google Ads",
        "type": "blog",
    },
    {
        "id": "google_merchant_blog",
        "name": "Google Merchant Center Blog",
        "url": "https://blog.google/products/shopping/rss/",
        "category": "Marketing",
        "platform": "Google Ads",
        "type": "blog",
    },
    {
        "id": "amazon_ads_api",
        "name": "Amazon Ads API Release Notes",
        "url": "https://d3a0d0y2hgofx6.cloudfront.net/rss/en-us/ad-api-rss.xml",
        "category": "Marketing",
        "platform": "Amazon Ads",
        "type": "releases",
    },
    {
        "id": "meta_business_blog",
        "name": "Meta Business Blog",
        "url": "https://www.facebook.com/business/news/rss/",
        "category": "Marketing",
        "platform": "Meta",
        "type": "blog",
    },
    {
        "id": "meta_newsroom",
        "name": "Meta Newsroom",
        "url": "https://about.fb.com/feed/",
        "category": "Marketing",
        "platform": "Meta",
        "type": "blog",
    },
    {
        "id": "pinterest_engineering",
        "name": "Pinterest Engineering",
        "url": "https://medium.com/feed/pinterest-engineering",
        "category": "Marketing",
        "platform": "Pinterest",
        "type": "blog",
    },
    {
        "id": "microsoft_ads_blog",
        "name": "Microsoft Advertising Blog",
        "url": "https://about.ads.microsoft.com/en-us/blog/rss",
        "category": "Marketing",
        "platform": "Microsoft Ads",
        "type": "blog",
    },
    {
        "id": "tiktok_newsroom",
        "name": "TikTok Newsroom",
        "url": "https://newsroom.tiktok.com/en-us/rss.xml",
        "category": "Marketing",
        "platform": "TikTok",
        "type": "blog",
    },
    {
        "id": "linkedin_engineering",
        "name": "LinkedIn Engineering Blog",
        "url": "https://engineering.linkedin.com/blog.rss",
        "category": "Marketing",
        "platform": "LinkedIn",
        "type": "blog",
    },
]

SCRAPERS = [
    {
        "id": "anthropic_news",
        "name": "Anthropic News",
        "url": "https://www.anthropic.com/news",
        "category": "AI",
        "platform": "Anthropic",
        "type": "blog",
    },
]

CACHE_TTL_SECONDS = 1800  # 30 minutes
DB_PATH = "data/feeds.duckdb"

PLATFORM_COLORS = {
    # AI models
    "Anthropic":     "#a78bfa",
    "OpenAI":        "#4ade80",
    "Google":        "#60a5fa",
    "Hugging Face":  "#fcd34d",
    "Ollama":        "#d4d4d8",
    "LangChain":     "#6ee7b7",
    "LlamaIndex":    "#c084fc",
    # Cloud
    "Google Cloud":  "#93c5fd",
    "AWS":           "#ff9900",
    # Data Tools
    "Snowflake":     "#22d3ee",
    "dbt":           "#fb923c",
    "Databricks":    "#f87171",
    "DuckDB":        "#fbbf24",
    "MongoDB":       "#00ed64",
    "Redis":         "#ff6b6b",
    "Apache Iceberg":"#67e8f9",
    "Delta Lake":    "#5eead4",
    "Polars":        "#fdba74",
    "Airbyte":       "#a5b4fc",
    # Orchestration
    "Apache Airflow":"#38bdf8",
    "Prefect":       "#e879f9",
    # Data Tools (new)
    "Streamlit":     "#ff4b4b",
    "Python":        "#4b8bbe",
    "Apache Spark":  "#e25a1c",
    # Orchestration (new)
    "Dagster":       "#a882dd",
    # Cloud (new)
    "Azure":         "#0078d4",
    # AI (new)
    "GitHub":        "#e8eaed",
    "Mistral AI":    "#ff7000",
    # Marketing
    "Amazon Ads":    "#1a9ce0",
    "Google Ads":    "#fbbc04",
    "Meta":          "#74b9ff",
    "Pinterest":     "#ff9eaa",
    "Microsoft Ads": "#00a4ef",
    "TikTok":        "#ee1d52",
    "LinkedIn":      "#0a66c2",
}
